name: mimicmotion
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip
  - pip:
      - diffusers==0.27.0
      - transformers==4.32.1
      - decord==0.6.0
      - einops
      - omegaconf
      - tqdm
      - matplotlib
      - opencv_python
      - onnxruntime-gpu==1.18.0
      - accelerate
      - av
      - huggingface_hub==0.24.7